name: interact
version: 0.1.0.0
synopsis: Functions to create interactive REPLs.
description: "DIY REPL: Prelude's 'interact' on steroids. Functions to create interactive REPLs."
homepage: https://github.com/epoberezkin/interact#readme
license: MIT
author: Evgeny Poberezkin
maintainer: evgeny@poberezkin.com
copyright: 2020 Evgeny Poberezkin
category: System, REPL
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - mtl

library:
  source-dirs: src

tests:
  interact-test:
    source-dirs: tests
    main: Test.hs
    dependencies:
      - bytestring
      - hspec
      - interact
      - main-tester
      - silently

ghc-options:
  - -Wall
  - -Wcompat
  - -Werror=incomplete-patterns
  - -Wredundant-constraints
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
