name: interact
version: 0.1.0.0
synopsis: instantly create REPL from any function
description: |
  This module provides functions to create interactive REPLs:
  .
  - stateless REPL from a single argument functions
  - REPL with state from plain state function or with State monad
  - REPL-fold from two-arguments functions, with the accumulator in the first argument
  .
  Each line you enter is 'read' into the argument type and sent to the function, with the result printed

homepage: https://github.com/epoberezkin/interact#readme
license: MIT
author: Evgeny Poberezkin
maintainer: evgeny@poberezkin.com
copyright: 2020 Evgeny Poberezkin
category: System, REPL
extra-source-files:
  - README.md
  - CHANGELOG.md

dependencies:
  - base >= 4.7 && < 5
  - mtl == 2.2.*

library:
  source-dirs: src

tests:
  interact-test:
    source-dirs: tests
    main: Test.hs
    dependencies:
      - bytestring == 0.10.*
      - hspec == 2.7.*
      - interact
      - main-tester == 0.2.*
      - silently == 1.2.*

ghc-options:
  - -Wall
  - -Wcompat
  - -Werror=incomplete-patterns
  - -Wredundant-constraints
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
