name: interact
version: 0.1.0.0
synopsis: Functions to create interactive REPLs.
description: "DIY REPL: Prelude's 'interact' on steroids. Functions to create interactive REPLs."
homepage: https://github.com/epoberezkin/interact#readme
license: MIT
author: Evgeny Poberezkin
maintainer: evgeny@poberezkin.com
copyright: 2020 Evgeny Poberezkin
category: System, REPL
extra-source-files:
  - README.md
  - CHANGELOG.md

dependencies:
  - base >= 4.7 && < 5
  - mtl >= 2.2 && < 2.3

library:
  source-dirs: src

tests:
  interact-test:
    source-dirs: tests
    main: Test.hs
    dependencies:
      - bytestring >= 0.10 && < 0.11
      - hspec >= 2.7 && < 2.8
      - interact
      - main-tester >= 0.2 && < 0.3
      - silently >= 1.2 && < 1.3

ghc-options:
  - -Wall
  - -Wcompat
  - -Werror=incomplete-patterns
  - -Wredundant-constraints
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
